

export interface Patient {
    name: string,
    race: string,
    gender: string,
    age: number,
    time_in_hospital: number,
    number_outpatient: number,
    number_emergency: number,
    number_inpatient: number,
    number_diagnoses: number,
    max_glu_serum: string,
    A1Cresult: string,

    metformin: string,
    repaglinide: string,
    nateglinide: string,
    chlorpropamide: string,
    glimepiride: string,
    acetohexamide: string,
    glipizide: string,
    glyburide: string,
    tolbutamide: string,
    pioglitazone: string,
    rosiglitazone: string,
    acarbose: string,
    miglitol: string,
    troglitazone: string,
    tolazamide: string, 
    examide: string,
    citoglipton: string,
    insulin: string,
    glyburide_metformin: string,
    glipizide_metformin: string,
    glimepiride_pioglitazone: string,
    metformin_rosiglitazone: string,
    metformin_pioglitazone: string,

    change: string,
    diabetesMed: string,
    readmitted: string,

    _diag_1: string,
    _diag_2: string,
    _diag_3: string,
}